name: build and release
on:
  push:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux --release
      - run: zip -r linux.zip build/linux/x64/release/bundle
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: linux.zip
          asset_name: serien-linux.zip
          tag: ${{ steps.date.outputs.date }}
          overwrite: true


  web:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter build web --release
      - run: zip -r web.zip build/web
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: web.zip
          asset_name: serien-web.zip
          tag: ${{ steps.date.outputs.date }}
          overwrite: true
          
  andoid:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: serien-android.apk
          tag: ${{ steps.date.outputs.date }}
          overwrite: true
